name: Build Salaty APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install dependencies
        run: npm install

      - name: Generate Android project
        run: npx expo prebuild --platform android --no-install

      - name: Build APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: salaty-apk
          path: android/app/build/outputs/apk/release/app-release.apk
